on: push
name: 🚀 AbaaPay production (AWS)
jobs:
  build:
    name: 🎉 AbaaPay Backend AWS Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: 📂 Sync files
      uses: action/setup-node@v4.3.4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        CI: true
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            sudo su - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            . ~/.nvm/nvm.sh

            nvm install node

            node -v
            npm -v

            yum update -y
            yum install git -y

            yum install -g pm2

            git --version
            git pull origin main
            cd ~/aspacelife-backend-nodejs

            npm install
            pm2 restart api

